import { StyleSheet } from "react-native";
import { theme } from "../../lib/theme";

export const adminHomeStyles = StyleSheet.create({
  interactionLayer: { flex: 1, position: "relative" },
  listContent: { paddingBottom: 12 },
  titleWithIcon: { flexDirection: "row", alignItems: "center", gap: 6 },
  sectionIcon: { color: "#2f4f7f" },
  sectionTitle: { color: "#122d54", fontSize: 18, fontWeight: "800", marginBottom: 6 },
  titleStrong: { color: "#173764", fontSize: 16, fontWeight: "800" },
  meta: { color: "#375276", fontSize: 13, fontWeight: "600", marginTop: 2 },
  metaStrong: { color: "#223f65", fontSize: 13, fontWeight: "700", marginTop: 2 },
  metaMuted: { color: "#637795", fontSize: 13, fontWeight: "600", marginTop: 2 },
  accordionHead: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  accordionIcon: { color: "#35517a", fontSize: 20, fontWeight: "800", marginTop: -4 },
  rowItem: { borderWidth: 1, borderColor: "#d5e1f4", borderRadius: 12, padding: 10, marginBottom: 8, backgroundColor: "#f5f9ff" },
  rowItemOverlay: { zIndex: 120, elevation: 12, overflow: "visible" },
  rowHead: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start", gap: 10 },
  rowMain: { flex: 1 },
  rowTitleWithMarker: { flexDirection: "row", alignItems: "center", gap: 7 },
  rowSubtitleWithIcon: { flexDirection: "row", alignItems: "center", gap: 4, marginTop: 2 },
  rowSubtitleText: { color: "#4e6384", fontSize: 12, fontWeight: "600" },
  rowMetaIcon: { color: "#5d7192" },
  rowActionsTop: { alignItems: "flex-end", position: "relative" },
  rowBadge: { borderRadius: 999, paddingHorizontal: 8, paddingVertical: 3, marginBottom: 6 },
  rowBadgeText: { fontSize: 10, fontWeight: "800", letterSpacing: 0.3 },
  badgeActive: { backgroundColor: "#d4f6e4", borderWidth: 1, borderColor: "#a4dfc1" },
  badgeActiveText: { color: "#0e4f31" },
  badgeNeutral: { backgroundColor: "#eef2f8", borderWidth: 1, borderColor: "#ccd8ea" },
  badgeNeutralText: { color: "#3f5475" },
  moreButton: { width: 28, height: 28, borderRadius: 8, borderWidth: 1, borderColor: "#c7d7f2", backgroundColor: "#ffffff", alignItems: "center", justifyContent: "center" },
  moreButtonText: { color: "#2e476c", fontWeight: "900", marginTop: -4, fontSize: 18, lineHeight: 18 },
  menuPanelInline: {
    marginTop: 8,
    borderWidth: 1,
    borderColor: "#d2dff2",
    borderRadius: 12,
    backgroundColor: "#ffffff",
    overflow: "hidden",
    shadowColor: "#1a3c73",
    shadowOpacity: 0.08,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
    elevation: 3,
  },
  menuItem: { paddingHorizontal: 12, paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: "#edf2fb" },
  menuItemRow: { flexDirection: "row", alignItems: "center", gap: 6 },
  menuIcon: { color: "#4f6384" },
  menuIconDanger: { color: "#9d2424" },
  menuItemText: { color: "#2a4468", fontSize: 12, fontWeight: "700" },
  menuItemDanger: { color: "#9d2424", fontSize: 12, fontWeight: "800" },
  expandBody: { marginTop: 8, paddingTop: 8, borderTopWidth: 1, borderTopColor: "#dbe5f4" },
  summaryRow: { flexDirection: "row", gap: 8 },
  summaryChip: { flex: 1, borderWidth: 1, borderColor: "#d2dff2", borderRadius: 10, padding: 8, backgroundColor: "#f8fbff" },
  summaryIcon: { color: "#4b6791", marginBottom: 4 },
  summaryLabel: { color: "#5b7092", fontSize: 11, fontWeight: "700" },
  summaryValue: { marginTop: 3, color: "#12335f", fontSize: 18, fontWeight: "800" },
  inlineRow: { flexDirection: "row", gap: 8, alignItems: "center", marginTop: 4, flexWrap: "wrap" },
  currentSessionPanel: {
    borderWidth: 1,
    borderColor: "#c6d9f5",
    borderRadius: 12,
    backgroundColor: "#f7fbff",
    padding: 10,
  },
  currentSessionTitle: {
    color: "#102d57",
    fontSize: 17,
    fontWeight: "900",
    letterSpacing: -0.2,
  },
  currentSessionTime: {
    marginTop: 4,
    color: "#2f4f78",
    fontSize: 13,
    fontWeight: "700",
  },
  currentSessionMetrics: {
    marginTop: 10,
    flexDirection: "row",
    gap: 8,
  },
  currentSessionMetricCard: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#d2def2",
    borderRadius: 10,
    backgroundColor: "#ffffff",
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  currentSessionMetricLabel: {
    color: "#587095",
    fontSize: 11,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.3,
  },
  currentSessionMetricValue: {
    marginTop: 3,
    color: "#143562",
    fontSize: 17,
    fontWeight: "900",
  },
  incomingItem: { borderWidth: 1, borderColor: "#d7e3f5", borderRadius: 10, backgroundColor: "#f8fbff", padding: 10, marginTop: 8 },
  incomingTitle: { color: "#183a72", fontSize: 15, fontWeight: "800" },
  incomingHead: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 6 },
  incomingRange: { color: "#2f4f78", fontSize: 12, fontWeight: "700" },
  incomingRow: { flexDirection: "row", alignItems: "center", gap: 8, marginTop: 4 },
  incomingEvent: { color: "#355070", fontSize: 13, fontWeight: "700" },
  typeDot: { width: 9, height: 9, borderRadius: 999 },
  typeDotMandatory: { backgroundColor: "#e2a93a" },
  typeDotOptional: { backgroundColor: "#43a26b" },
  memberStatusDotActive: { backgroundColor: "#43a26b" },
  memberStatusDotInactive: { backgroundColor: "#b8c6dc" },
  detailRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 10,
    marginTop: 6,
  },
  detailLabel: {
    color: "#5b7092",
    fontSize: 12,
    fontWeight: "700",
    minWidth: 62,
  },
  detailValue: {
    flex: 1,
    textAlign: "right",
    color: "#2e476c",
    fontSize: 12,
    fontWeight: "700",
  },
  actionChip: { borderWidth: 1, borderColor: "#b8cbe8", borderRadius: 10, backgroundColor: "#ffffff", minHeight: 40, minWidth: 90, paddingHorizontal: 10, alignItems: "center", justifyContent: "center" },
  actionChipActive: { borderColor: "#a4dfc1", backgroundColor: "#d4f6e4" },
  actionChipText: { color: "#2e476c", fontWeight: "700" },
  actionChipTextActive: { color: "#0e4f31" },
  actionPrimary: { borderWidth: 1, borderColor: theme.primary, borderRadius: 10, backgroundColor: theme.primary, minHeight: 40, minWidth: 92, paddingHorizontal: 10, alignItems: "center", justifyContent: "center" },
  actionPrimaryText: { color: "#ffffff", fontWeight: "700" },
  actionSecondary: { borderWidth: 1, borderColor: "#b8cbe8", borderRadius: 10, backgroundColor: "#ffffff", minHeight: 40, minWidth: 86, paddingHorizontal: 10, alignItems: "center", justifyContent: "center" },
  actionSecondaryText: { color: "#2e476c", fontWeight: "700" },
  searchRow: { flexDirection: "row", gap: 8, alignItems: "center" },
  searchInput: { flex: 1, borderWidth: 1, borderColor: "#a8b8d3", borderRadius: 10, backgroundColor: "#fff", color: theme.ink, paddingVertical: 10, paddingHorizontal: 10, fontSize: 14 },
  searchButton: { minHeight: 40, minWidth: 72, borderRadius: 10, borderWidth: 1, borderColor: theme.primary, backgroundColor: theme.primary, alignItems: "center", justifyContent: "center", paddingHorizontal: 10 },
  searchButtonText: { color: "#fff", fontWeight: "700", fontSize: 12 },
  profileLogoutButton: {
    minHeight: 44,
    borderWidth: 1,
    borderColor: "#f0bebe",
    borderRadius: 10,
    backgroundColor: "#fff1f1",
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 8,
  },
  profileLogoutIcon: { color: "#9d2424" },
  profileLogoutText: { color: "#9d2424", fontWeight: "800", fontSize: 14 },
  dialogBackdrop: {
    flex: 1,
    backgroundColor: "rgba(11, 26, 47, 0.45)",
    alignItems: "center",
    justifyContent: "center",
    padding: 16,
  },
  dialogCard: {
    width: "100%",
    maxWidth: 420,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#c8d7ef",
    backgroundColor: "#ffffff",
    padding: 16,
  },
  dialogIconWrap: {
    width: 44,
    height: 44,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#f2f7ff",
    marginBottom: 10,
  },
  dialogIcon: {
    color: "#35517a",
  },
  dialogIconPrimary: {
    color: "#1f4f9a",
  },
  dialogIconDanger: {
    color: "#b12f2f",
  },
  dialogTitle: {
    color: "#132f57",
    fontSize: 18,
    fontWeight: "800",
  },
  dialogMessage: {
    marginTop: 8,
    color: "#395474",
    fontSize: 14,
    fontWeight: "600",
    lineHeight: 20,
  },
  dialogActions: {
    marginTop: 16,
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 8,
  },
  dialogCancelButton: {
    minHeight: 40,
    minWidth: 84,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#c0d0e8",
    backgroundColor: "#ffffff",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 12,
  },
  dialogCancelText: {
    color: "#2e476c",
    fontWeight: "700",
    fontSize: 13,
  },
  dialogConfirmButton: {
    minHeight: 40,
    minWidth: 110,
    borderRadius: 10,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 12,
  },
  dialogConfirmPrimary: {
    borderColor: "#1f4f9a",
    backgroundColor: "#1f4f9a",
  },
  dialogConfirmDanger: {
    borderColor: "#b12f2f",
    backgroundColor: "#b12f2f",
  },
  dialogConfirmText: {
    color: "#ffffff",
    fontWeight: "800",
    fontSize: 13,
  },
});
